version: '3'
services:
  database:
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    build:
      context: .
      dockerfile: docker/database.dockerfile
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: database
        target: /var/lib/postgresql/data

volumes:
  database: